export const THEMES = {
  rose: {
    key: "rose",
    name: "Rose",
    background: "#FFFFFF",
    card: "#F7EAE4",
    inputBackground: "#FBF1ED",
    textColor: "#4A2C36",
    textMuted: "#9B7E84",
    lightButton: "#E8A0B8",
    darkButton: "#D4638D",
    border: "#EBD9D2",
    white: "#FFFFFF",
    dark: "#111111",
  },
  sage: {
    key: "sage",
    name: "Sage",
    background: "#F7FBF4",
    card: "#E2EFD9",
    inputBackground: "#EDF5E5",
    textColor: "#263D20",
    textMuted: "#6E9E65",
    lightButton: "#A8CE99",
    darkButton: "#4D8A3F",
    border: "#CBE2C0",
    white: "#FFFFFF",
    dark: "#111111",
  },
  lavender: {
    key: "lavender",
    name: "Lavender",
    background: "#FAF8FF",
    card: "#EDE8F7",
    inputBackground: "#F3F0FB",
    textColor: "#2E2156",
    textMuted: "#8B7FAD",
    lightButton: "#C4B4E8",
    darkButton: "#7758CC",
    border: "#DDD3F4",
    white: "#FFFFFF",
    dark: "#111111",
  },
  midnight: {
    key: "midnight",
    name: "Midnight",
    background: "#0F0F17",
    card: "#1C1C2C",
    inputBackground: "#252538",
    textColor: "#E8E3F4",
    textMuted: "#7872A0",
    lightButton: "#3D3566",
    darkButton: "#9B84D8",
    border: "#2D2B44",
    white: "#FFFFFF",
    dark: "#111111",
  },
};

export const THEME_LIST = Object.values(THEMES);
